spring.application.name=ms-pedidos

spring.profiles.active=test
spring.jpa.open-in-vlan=false

# Eureka Client: registra no Eureka Server e busca o catálogo (registry)

# config do Eureka Client (ms-pedidos)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Endereço do Eureka Server (defaultZone é camelCase)
# localhost 8761, onde o Eureka Server está recebendo as requisições
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Porta aleatória para permitir múltiplas instâncias (escala local)
server.port=0

# Identificador da instância (evita sobrescrever no registry)
eureka.instance.instance-id=${spring.application.name}:${random.int[1,99]}
