spring.application.name=eureka-server

# Eureka Server (Service Registry)
# - centraliza o catálogo de instâncias (endereços/metadados) para discovery
# - o próprio server NÃO deve se registrar nem buscar o registry como cliente.

# Porta padrão do Eureka Server (dashboard e endpoint /eureka).
server.port=8761

# Como é o SERVER, não registra a si mesmo no Eureka.
eureka.client.register-with-eureka=false

# Como é o SERVER, não precisa buscar/cachar o registry.
eureka.client.fetch-registry=false

# eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
# Versão recomendada (evita erro ao trocar porta)
# defaultZone precisa ser exatamente assim (camelCase), pois serviceUrl é um Map.
eureka.client.serviceUrl.defaultZone=http://localhost:${server.port}/eureka/